[tool.poetry]
name = "tbot-test-task"
version = "0.1.0"
description = ""
authors = ["Igor-Mozharov <r5@ukr.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
python-telegram-bot = "^22.0"
mindee = "^4.21.1"
openai = "^1.76.1"
google-generativeai = "^0.8.5"
aiohttp = "^3.11.18"
flask = "^3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
